### PR TITLE
Updated various aspects of the plugin

### PR DESCRIPTION
**Pull request by ShadowRanger**
I decided to spend a few hours doing some work on this plugin as it has not been updated in a while. I have made a fair few changes which I have listed below. I understand that you may not like some of the changes/additions but there are some good ones so I guess you could revert the parts you don't like.

Before I provide the changes that I have made, I'd like to briefly go over some of the major ones and why I did them. First of all is building the plugin with Java 7. The reason I thought this would be a good idea is that not only was this plugin on a fairly old version (Java 5) but also that Java 7 seems to be the most commonly used Java version used by servers these days, at least based on what I've seen and from mcstats.org. The other change I wanted to mention was changing from CraftBukkit to Bukkit. After going through all the code I realised that CraftBukkit was not used at all. For this reason, I thought that the plugin should just depend on the Bukkit API instead so that's why I did it.

Changes:
- Made the plugin build with Java 7
- Updated Bukkit API version to 1.8-R0.1-SNAPSHOT
- Updated Maven Compiler Plugin version
- Made plugin depend on Bukkit instead of CraftBukkit as the plugin doesn't use any of CraftBukkit's features
- Renamed loadFromTextfile() to loadFromTextFile() in InventoryIO
- Deprecated loadFromTextFile() in InventoryIO
- Uppercased Teller Enums
- Separated Commands into their own classes (for organisation purposes)
- Refactored Commands
- Added missing permission to plugin.yml: alphachest.chest.creativeMode
- Made Teller Message colors configurable (new config options added)
- Cleaned up pom.xml
- Cleaned up plugin.yml
- Updated README.md
- General code refactoring

If you have any questions, concerns or requests in regards to this pull request, please let me know. Thanks.

### CODE REVIEW

**Comment by Brianetta** [comment]
OK, this didn't compile, because not all of the Type constants had been converted to upper case.

https://github.com/Brianetta/Bukkit-AlphaChest/commits/PR-12 (5a6cb1d7701878c9a2f97a73978d37a12b405436) addresses this. If you're happy with the changes in there, just push them to this request and I'll get it merged.

**Comment by ShadowRanger** [comment]
Oops I didn't see that I hadn't replaced all the type constants; sorry. I'm happy with the changes you made, no problems at all. Also, just out of curiosity, why did you say this embarrasses you? I apologize if I did anything to do that, I had no intentions of doing so. Just trying to contribute and help.

**Comment by ShadowRanger** [comment]
One thing I am unsure about is whether your happy with updating the plugin to compile with Java 7. I wasn't sure whether it would be better to use that or Java 6 for compatibility reasons. If you would prefer Java 6 I'd be happy to change the pull request to use that instead. Additionally, the plugin could also build with Spigot's Bukkit for Minecraft 1.8.3 as that has now been released although whether you would like that change is up to you.

**Comment by Brianetta** [comment]
You did not embarrass me. I did. My spelling is usually of a higher standard.

Java 7 is definitely a good thing. Mojang are keen to make use of it, and we should too.

**Comment by Brianetta** [comment]
Closing this; You might need to reset your master branch because off all the additional merge commits.

**Pull request closed without merging**
